In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, "calki", 5+6j])

array(['1', '2', '3', 'calki', '(5+6j)'], dtype='<U64')

In [4]:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [5]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
np.array([[0,1], [2,3]])

array([[0, 1],
       [2, 3]])

In [7]:
np.array([(0,1), (2,3)])

array([[0, 1],
       [2, 3]])

In [8]:
q = np.array([(1,2),(4,5)], dtype=[("a","<i2"), ("b", "<i8")])
q

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [9]:
type(q[0][0])

numpy.int16

In [10]:
type(q[0][1])

numpy.int64

In [11]:
q

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [12]:
a = np.array([[1,2],[3,4]])
# np.mat(a)
mat = np.matrix(a)
mat

matrix([[1, 2],
        [3, 4]])

In [13]:
l = [1, 2, 3, 4, 5]
print(np.array(l))
print(np.asarray(l))
print(np.asanyarray(l))

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [14]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [15]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [16]:
issubclass(np.matrix, np.ndarray)

True

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
x = a

In [19]:
y = np.copy(a)

In [20]:
a[0] = 0

In [21]:
a

array([[0, 0],
       [3, 4]])

In [22]:
x

array([[0, 0],
       [3, 4]])

In [23]:
y

array([[1, 2],
       [3, 4]])

In [24]:
x[0:1]

array([[0, 0]])

In [25]:
a[-1]

array([3, 4])

In [26]:
np.fromfunction(lambda i, j: i ==j, (4, 4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [27]:
a = (i*i for i in range(5))
a

<generator object <genexpr> at 0x7f904003c660>

In [28]:
np.fromiter(a, dtype=int)

array([ 0,  1,  4,  9, 16])

In [29]:
np.fromstring('1,3,5,6,7', sep=",", dtype=int)

array([1, 3, 5, 6, 7])

In [30]:
a = np.array([[1, 2], [3, 4]])

In [31]:
a.ndim

2

In [32]:
a.size

4

In [33]:
a.shape

(2, 2)

In [34]:
a.dtype

dtype('int64')

In [35]:
np.arange(8.8)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [36]:
np.arange(8.8, 12, 0.2)

array([ 8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8])

In [37]:
np.arange(9.8, 6.5, -0.3)

array([9.8, 9.5, 9.2, 8.9, 8.6, 8.3, 8. , 7.7, 7.4, 7.1, 6.8, 6.5])

In [38]:
np.arange(9, 6, -1)

array([9, 8, 7])

In [39]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
np.ones((2,3,3)) + 6

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])

In [44]:
np.empty((3, 4))

array([[9.8, 9.5, 9.2, 8.9],
       [8.6, 8.3, 8. , 7.7],
       [7.4, 7.1, 6.8, 6.5]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.linspace([1, 6], 4, axis=1)

array([[1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
        1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
        1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
        1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
        2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
        2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
        2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
        3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
        3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
        3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ],
       [6.        , 5.95918367, 5.91836735, 5.87755102, 5.83673469,
        5.79591837, 5.75510204, 5.71428571, 5.67346939, 5.63265306,
        5.59183673, 5.55102041, 5.51020408, 5.46938776, 5.42857143,
        5.3877551 , 5.34693878, 5.30612245, 5.26530612, 5.2244898 ,
        5.18367347, 5.14285714, 5.10204082, 5.0

In [47]:
np.linspace([1], [2])

array([[1.        ],
       [1.02040816],
       [1.04081633],
       [1.06122449],
       [1.08163265],
       [1.10204082],
       [1.12244898],
       [1.14285714],
       [1.16326531],
       [1.18367347],
       [1.20408163],
       [1.2244898 ],
       [1.24489796],
       [1.26530612],
       [1.28571429],
       [1.30612245],
       [1.32653061],
       [1.34693878],
       [1.36734694],
       [1.3877551 ],
       [1.40816327],
       [1.42857143],
       [1.44897959],
       [1.46938776],
       [1.48979592],
       [1.51020408],
       [1.53061224],
       [1.55102041],
       [1.57142857],
       [1.59183673],
       [1.6122449 ],
       [1.63265306],
       [1.65306122],
       [1.67346939],
       [1.69387755],
       [1.71428571],
       [1.73469388],
       [1.75510204],
       [1.7755102 ],
       [1.79591837],
       [1.81632653],
       [1.83673469],
       [1.85714286],
       [1.87755102],
       [1.89795918],
       [1.91836735],
       [1.93877551],
       [1.959

In [48]:
a = np.linspace(4, 7, 40)

In [49]:
a.ndim

1

In [50]:
a.shape 

(40,)

In [55]:
a.reshape(1, 2, 20)
# number of element to reshape is always equal to after reshapeing
# e.g. 1 * 2 * 20 == 40 (a.shape)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [57]:
np.logspace(2, 5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [58]:
np.random.rand(3) # it returns data in uniform distribution

array([0.17103652, 0.9336967 , 0.50205091])

In [60]:
np.random.randn(3) # it returns data in standard normal distribution

array([1.40899721, 0.55856717, 0.45601575])

In [61]:
np.random.randn(2, 3)

array([[ 1.24304686,  0.79153519, -0.22225507],
       [ 0.12259726,  1.08689307, -0.02868163]])

In [62]:
np.random.randint(5)

3

In [68]:
a = np.random.randint(5,60, (5, 2))
a

array([[50, 22],
       [56, 56],
       [35, 59],
       [44, 26],
       [18, 29]])

In [73]:
a.reshape(10, -1) # -1 takes dynamically 2nd diamention

array([[50],
       [22],
       [56],
       [56],
       [35],
       [59],
       [44],
       [26],
       [18],
       [29]])

In [76]:
a.reshape(1, -645) # basically any minus number will work

array([[50, 22, 56, 56, 35, 59, 44, 26, 18, 29]])

In [77]:
a.max()

59

In [78]:
a.min()

18

In [83]:
a = np.random.randint(4, 100, (5, 5))
a

array([[72, 44, 38, 97, 46],
       [ 5, 99, 11, 74, 64],
       [20, 53, 14, 46, 50],
       [30, 35, 25, 78, 85],
       [60,  7,  4, 51, 84]])

In [84]:
a[3:,3:]

array([[78, 85],
       [51, 84]])

In [85]:
a[:,[2,4]]

array([[38, 46],
       [11, 64],
       [14, 50],
       [25, 85],
       [ 4, 84]])

In [86]:
a

array([[72, 44, 38, 97, 46],
       [ 5, 99, 11, 74, 64],
       [20, 53, 14, 46, 50],
       [30, 35, 25, 78, 85],
       [60,  7,  4, 51, 84]])

In [88]:
a[a < 10]

array([5, 7, 4])

In [89]:
a1 = np.random.randint(2, 4, (3,3))
a2 = np.random.randint(2, 4, (3,3))

In [90]:
a1

array([[2, 2, 3],
       [3, 2, 3],
       [2, 2, 2]])

In [91]:
a2

array([[2, 2, 3],
       [2, 3, 3],
       [2, 3, 2]])

In [92]:
a1 * a2
# index wise multiplication

array([[4, 4, 9],
       [6, 6, 9],
       [4, 6, 4]])

In [93]:
a1.dot(a2)
# metrix multiplication

array([[14, 19, 18],
       [16, 21, 21],
       [12, 16, 16]])

In [95]:
a1@a2
# matrix multiplication

array([[14, 19, 18],
       [16, 21, 21],
       [12, 16, 16]])

In [96]:
a1/0

/tmp/ipykernel_52988/1504525615.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [97]:
a1 ** 2

array([[4, 4, 9],
       [9, 4, 9],
       [4, 4, 4]])

In [98]:
a1

array([[2, 2, 3],
       [3, 2, 3],
       [2, 2, 2]])

In [99]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

In [104]:
a + b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [105]:
a * b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
a + np.array([1, 2, 3]).reshape(3, 1)

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [112]:
np.array([1, 2, 3]).T
# not able to transpose because only one diamention given

array([1, 2, 3])

In [116]:
print(a1)
print(np.sqrt(a1))

[[2 2 3]
 [3 2 3]
 [2 2 2]]
[[1.41421356 1.41421356 1.73205081]
 [1.73205081 1.41421356 1.73205081]
 [1.41421356 1.41421356 1.41421356]]


In [117]:
np.exp(a1)

array([[ 7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [118]:
np.log10(a1)

array([[0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.30103   , 0.30103   ]])

In [124]:
np.random.seed(10)

In [126]:
np.random.rand(2, 4)

array([[0.22479665, 0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335, 0.00394827]])