In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, "calki", 5+6j])

array(['1', '2', '3', 'calki', '(5+6j)'], dtype='<U64')

In [4]:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [5]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
np.array([[0,1], [2,3]])

array([[0, 1],
       [2, 3]])

In [7]:
np.array([(0,1), (2,3)])

array([[0, 1],
       [2, 3]])

In [8]:
q = np.array([(1,2),(4,5)], dtype=[("a","<i2"), ("b", "<i8")])
q

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [9]:
type(q[0][0])

numpy.int16

In [10]:
type(q[0][1])

numpy.int64

In [11]:
q

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
a = np.array([[1,2],[3,4]])
# np.mat(a)
mat = np.matrix(a)
mat

matrix([[1, 2],
        [3, 4]])

In [15]:
l = [1, 2, 3, 4, 5]
print(np.array(l))
print(np.asarray(l))
print(np.asanyarray(l))

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [19]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [20]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [21]:
issubclass(np.matrix, np.ndarray)

True

In [22]:
a

array([[1, 2],
       [3, 4]])

In [23]:
x = a

In [24]:
y = np.copy(a)

In [25]:
a[0] = 0

In [26]:
a

array([[0, 0],
       [3, 4]])

In [27]:
x

array([[0, 0],
       [3, 4]])

In [28]:
y

array([[1, 2],
       [3, 4]])

In [29]:
x[0:1]

array([[0, 0]])

In [30]:
a[-1]

array([3, 4])

In [31]:
np.fromfunction(lambda i, j: i ==j, (4, 4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [33]:
a = (i*i for i in range(5))
a

<generator object <genexpr> at 0x7faef4781ac0>

In [34]:
np.fromiter(a, dtype=int)

array([ 0,  1,  4,  9, 16])

In [36]:
np.fromstring('1,3,5,6,7', sep=",", dtype=int)

array([1, 3, 5, 6, 7])

In [37]:
a = np.array([[1, 2], [3, 4]])

In [38]:
a.ndim

2

In [39]:
a.size

4

In [40]:
a.shape

(2, 2)

In [44]:
a.dtype

dtype('int64')

In [53]:
np.arange(8.8)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [55]:
np.arange(8.8, 12, 0.2)

array([ 8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8])

In [57]:
np.arange(9.8, 6.5, -0.3)

array([9.8, 9.5, 9.2, 8.9, 8.6, 8.3, 8. , 7.7, 7.4, 7.1, 6.8, 6.5])

In [58]:
np.arange(9, 6, -1)

array([9, 8, 7])

In [59]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
np.ones((2,3,3)) + 6

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])

In [68]:
np.empty((3, 4))

array([[9.8, 9.5, 9.2, 8.9],
       [8.6, 8.3, 8. , 7.7],
       [7.4, 7.1, 6.8, 6.5]])

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.linspace([1, 6], 4, axis=1)

array([[1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
        1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
        1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
        1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
        2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
        2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
        2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
        3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
        3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
        3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ],
       [6.        , 5.95918367, 5.91836735, 5.87755102, 5.83673469,
        5.79591837, 5.75510204, 5.71428571, 5.67346939, 5.63265306,
        5.59183673, 5.55102041, 5.51020408, 5.46938776, 5.42857143,
        5.3877551 , 5.34693878, 5.30612245, 5.26530612, 5.2244898 ,
        5.18367347, 5.14285714, 5.10204082, 5.0

In [75]:
np.linspace([1], [2])

array([[1.        ],
       [1.02040816],
       [1.04081633],
       [1.06122449],
       [1.08163265],
       [1.10204082],
       [1.12244898],
       [1.14285714],
       [1.16326531],
       [1.18367347],
       [1.20408163],
       [1.2244898 ],
       [1.24489796],
       [1.26530612],
       [1.28571429],
       [1.30612245],
       [1.32653061],
       [1.34693878],
       [1.36734694],
       [1.3877551 ],
       [1.40816327],
       [1.42857143],
       [1.44897959],
       [1.46938776],
       [1.48979592],
       [1.51020408],
       [1.53061224],
       [1.55102041],
       [1.57142857],
       [1.59183673],
       [1.6122449 ],
       [1.63265306],
       [1.65306122],
       [1.67346939],
       [1.69387755],
       [1.71428571],
       [1.73469388],
       [1.75510204],
       [1.7755102 ],
       [1.79591837],
       [1.81632653],
       [1.83673469],
       [1.85714286],
       [1.87755102],
       [1.89795918],
       [1.91836735],
       [1.93877551],
       [1.959