In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, "calki", 5+6j])

array(['1', '2', '3', 'calki', '(5+6j)'], dtype='<U64')

In [4]:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [5]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
np.array([[0,1], [2,3]])

array([[0, 1],
       [2, 3]])

In [7]:
np.array([(0,1), (2,3)])

array([[0, 1],
       [2, 3]])

In [9]:
q = np.array([(1,2),(4,5)], dtype=[("a","<i2"), ("b", "<i8")])
q

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [10]:
type(q[0][0])

numpy.int16

In [11]:
type(q[0][1])

numpy.int64

In [12]:
q

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [16]:
a = np.array([[1,2],[3,4]])
# np.mat(a)
np.matrix(a)

matrix([[1, 2],
        [3, 4]])